---

- name: Disable pve-enterprise repository
  ansible.builtin.deb822_repository:
    name: pve-enterprise
    enabled: false
    state: present

- name: Add pve-no-subscription repository
  ansible.builtin.deb822_repository:
    name: pve-no-subscription
    uris: http://download.proxmox.com/debian/pve
    suites: '{{ ansible_facts["distribution_release"] }}'
    components: pve-no-subscription
    signed_by: /usr/share/keyrings/proxmox-archive-keyring.gpg
    state: present
  notify: Update packages

- name: Flush handlers
  ansible.builtin.meta: flush_handlers

- name: Install Intel microcode
  when: ansible_facts["processor"] | lower is search('intel')
  ansible.builtin.apt:
    name: intel-microcode
    state: present

- name: Install AMD microcode
  when: ansible_facts["processor"] | lower is search('amd')
  ansible.builtin.apt:
    name: amd64-microcode
    state: present
